import { editor } from 'monaco-editor'

export type EditorThemeConfig = editor.IStandaloneThemeData

const AuraDarkTheme: EditorThemeConfig = {
  base: 'vs-dark',
  inherit: true,
  colors: {
    focusBorder: '#a394f033',
    foreground: '#edecee',
    errorForeground: '#ff6767',
    'widget.shadow': '#0f0f0f',
    'selection.background': '#3d375e7f',
    'titleBar.activeBackground': '#121016',
    'titleBar.border': '#000000',
    'titleBar.inactiveBackground': '#2d2b38',
    'statusBar.background': '#121016',
    'statusBar.foreground': '#adacae',
    'statusBar.border': '#000000',
    'statusBar.debuggingForeground': '#15141b',
    'statusBar.debuggingBackground': '#a19c77',
    'statusBarItem.activeBackground': '#a277ff',
    'dropdown.background': '#15141b',
    'dropdown.border': '#3b334b',
    'dropdown.foreground': '#cdccce',
    'input.background': '#15141b',
    'input.border': '#3b334b',
    'input.foreground': '#cdccce',
    'input.placeholderForeground': '#af8aff7f',
    'inputOption.activeBorder': '#a277ff',
    'button.background': '#61ffca',
    'button.foreground': '#15141b',
    'button.hoverBackground': '#49c29a',
    'list.activeSelectionBackground': '#2e2b38',
    'list.activeSelectionForeground': '#a277ff',
    'list.focusBackground': '#3b334b',
    'list.focusForeground': '#a277ff',
    'list.highlightForeground': '#ffca85',
    'list.hoverBackground': '#3b334b',
    'list.hoverForeground': '#edecee',
    'list.inactiveSelectionBackground': '#2e2b38',
    'list.inactiveSelectionForeground': '#a277ff',
    'editor.background': '#15141b',
    'editor.foreground': '#edecee',
    'editorLineNumber.foreground': '#a394f033',
    'editorIndentGuide.activeBackground': '#6d6d6d',
    'editorCursor.foreground': '#a277ff',
    'editor.selectionBackground': '#3d375e7f',
    'editor.selectionHighlightBackground': '#3d375e7f',
    'editor.inactiveSelectionBackground': '#3d375e7f',
    'editor.wordHighlightBackground': '#3d375e7f',
    'editor.wordHighlightStrongBackground': '#3d375e7f',
    'editor.findMatchBackground': '#3d375e7f',
    'editor.findMatchHighlightBackground': '#3d375e7f',
    'editor.findRangeHighlightBackground': '#3d375e7f',
    'editor.lineHighlightBackground': '#a394f033',
    'editor.lineHighlightBorder': '#a394f000',
    'editor.stackFrameHighlightBackground': '#353424',
    'editorInlayHint.background': '#2e2b38',
    'editorInlayHint.foreground': '#cdccce',
    'editorLink.activeForeground': '#a277ff',
    'editorWhitespace.foreground': '#2d2d2d',
    'editorIndentGuide.background': '#2d2d2d',
    'editorBracketMatch.border': '#a277ff',
    'editorError.foreground': '#ff6767',
    'editorError.border': '#ffffff00',
    'editorWarning.foreground': '#ffca85',
    'editorWarning.border': '#ffffff00',
    'editorGutter.modifiedBackground': '#ffca85',
    'editorGutter.addedBackground': '#61ffca',
    'editorGutter.deletedBackground': '#ff6767',
    'editorWidget.background': '#121016',
    'editorWidget.border': '#2d2d2d',
    'editorSuggestWidget.background': '#121016',
    'editorSuggestWidget.border': '#2d2d2d',
    'editorSuggestWidget.foreground': '#cdccce',
    'editorSuggestWidget.highlightForeground': '#61ffca',
    'editorSuggestWidget.selectedBackground': '#4d4d4d',
    'editorHoverWidget.background': '#121016',
    'editorHoverWidget.border': '#2d2d2d',
    'editorGroup.border': '#000000',
    'editorGroup.dropBackground': '#3d375e7f',
    'editorGroupHeader.tabsBackground': '#15141b',
    'editorGroupHeader.tabsBorder': '#000000',
    'tab.activeBackground': '#00000000',
    'tab.activeForeground': '#61ffca',
    'tab.border': '#000000',
    'tab.inactiveBackground': '#15141b',
    'tab.inactiveForeground': '#6d6d6d',
    'tab.activeBorderTop': '#61ffca',
    'panel.border': '#000000',
    'panelTitle.activeBorder': '#61ffca',
    'panelTitle.activeForeground': '#cdccce',
    'activityBar.background': '#15141b',
    'activityBar.foreground': '#61ffca',
    'activityBar.inactiveForeground': '#525156',
    'activityBar.border': '#000000',
    'activityBarBadge.background': '#a277ff',
    'activityBarBadge.foreground': '#15141b',
    'activityBar.activeBorder': '#a277ff',
    'badge.foreground': '#15141b',
    'badge.background': '#a277ff',
    'sideBar.background': '#110f18',
    'sideBar.foreground': '#cdccce',
    'sideBar.border': '#000000',
    'sideBarTitle.foreground': '#adacae',
    'sideBarSectionHeader.background': '#15141b',
    'sideBarSectionHeader.foreground': '#adacae',
    'progressBar.background': '#61ffca',
    'scrollbar.shadow': '#15141b',
    'scrollbarSlider.activeBackground': '#3d375e7f',
    'scrollbarSlider.background': '#a394f033',
    'scrollbarSlider.hoverBackground': '#a394f033',
    'terminal.background': '#15141b',
    'terminal.foreground': '#cdccce',
    'terminal.ansiBlack': '#15141b',
    'terminal.ansiBlue': '#a277ff',
    'terminal.ansiBrightBlack': '#2d2d2d',
    'terminal.ansiBrightBlue': '#a277ff',
    'terminal.ansiBrightCyan': '#61ffca',
    'terminal.ansiBrightGreen': '#a277ff',
    'terminal.ansiBrightMagenta': '#61ffca',
    'terminal.ansiBrightRed': '#ffca85',
    'terminal.ansiBrightWhite': '#edecee',
    'terminal.ansiBrightYellow': '#ffca85',
    'terminal.ansiCyan': '#a277ff',
    'terminal.ansiGreen': '#61ffca',
    'terminal.ansiMagenta': '#61ffca',
    'terminal.ansiRed': '#ff6767',
    'terminal.ansiWhite': '#cdccce',
    'terminal.ansiYellow': '#ffca85',
    'terminal.selectionBackground': '#3d375e7f',
    'terminalCursor.background': '#2d2d2d',
    'terminalCursor.foreground': '#adacae',
    'gitDecoration.modifiedResourceForeground': '#ffca85',
    'gitDecoration.deletedResourceForeground': '#ff6767',
    'gitDecoration.untrackedResourceForeground': '#61ffca',
    'gitDecoration.ignoredResourceForeground': '#4d4d4d',
    'gitDecoration.conflictingResourceForeground': '#a277ff',
    'diffEditor.insertedTextBackground': '#00d89023',
    'diffEditor.removedTextBackground': '#ff474720',
    'tree.indentGuidesStroke': '#4d4d4d'
  },
  rules: [
    { token: 'keyword', foreground: '#a277ff' },
    { token: 'storage', foreground: '#a277ff' },
    { token: 'support', foreground: '#a277ff' },
    { token: 'entity.name.tag', foreground: '#a277ff' },
    { token: 'variable.language', foreground: '#a277ff' },
    { token: 'keyword.control.flow', foreground: '#a277ff' },
    { token: 'storage.modifier', foreground: '#a277ff' },
    { token: 'keyword.operator', foreground: '#a277ff' },
    { token: 'entity.other.attribute-name.class.css', foreground: '#a277ff' },
    { token: 'entity.other.keyframe-offset', foreground: '#a277ff' },
    { token: 'markup.heading', foreground: '#a277ff' },
    { token: 'markup.underline.link', foreground: '#a277ff' },
    { token: 'variable.other.env', foreground: '#a277ff' },
    { token: 'punctuation.definition.list.begin.markdown', foreground: '#a277ff' },
    { token: 'punctuation.definition.italic.markdown', foreground: '#a277ff' },
    { token: 'constant.length.units.css', foreground: '#a277ff' },
    { token: 'constant.percentage.units.css', foreground: '#a277ff' },

    { token: 'string', foreground: '#61ffca' },
    { token: 'markup.inserted', foreground: '#61ffca' },
    { token: 'markup.raw', foreground: '#61ffca' },
    { token: 'constant', foreground: '#61ffca' },
    { token: 'source.env', foreground: '#61ffca' },
    { token: 'support.type.builtin.graphql', foreground: '#61ffca' },
    { token: 'variable.other.quoted.double', foreground: '#61ffca' },
    { token: 'markup.inline.raw.string.markdown', foreground: '#61ffca' },
    { token: 'entity.other.attribute-name.id.css', foreground: '#61ffca' },
    { token: 'meta.jsx.children', foreground: '#61ffca' },
    { token: 'JSXNested', foreground: '#61ffca' },

    { token: 'markup.changed', foreground: '#ffca85' },
    { token: 'entity', foreground: '#ffca85' },
    { token: 'entity.name.function', foreground: '#ffca85' },
    { token: 'entity.name.function.elixir', foreground: '#ffca85' },
    { token: 'entity.name.function-call.elixir', foreground: '#ffca85' },
    { token: 'support.class.component.tsx', foreground: '#ffca85' },
    { token: 'support.class.component.open.jsx', foreground: '#ffca85' },
    { token: 'support.class.component.close.jsx', foreground: '#ffca85' },
    { token: 'meta.function-call.generic.python', foreground: '#ffca85' },
    { token: 'entity.name.section.markdown', foreground: '#ffca85' },
    { token: 'storage.type.annotation.dart', foreground: '#ffca85' },

    { token: 'invalid', foreground: '#ff6767' },
    { token: 'markup.deleted', foreground: '#ff6767' },

    { token: 'meta.object-literal.key', foreground: '#f694ff' },
    { token: 'variable.object.property', foreground: '#f694ff' },
    { token: 'variable.other.property', foreground: '#f694ff' },
    { token: 'variable.other.object.property', foreground: '#f694ff' },
    { token: 'variable.other.constant.property', foreground: '#f694ff' },
    { token: 'meta.type.annotation', foreground: '#f694ff' },
    { token: 'support.type.property-name.css', foreground: '#f694ff' },
    { token: 'support.type.vendored', foreground: '#f694ff' },
    { token: 'constant.language.symbol.elixir', foreground: '#f694ff' },
    { token: 'variable.graphql', foreground: '#f694ff' },
    { token: 'meta.attribute.python', foreground: '#f694ff' },
    { token: 'source.dart', foreground: '#f694ff' },

    { token: 'variable', foreground: '#edecee' },
    { token: 'markup.list', foreground: '#edecee' },
    { token: 'support.constant.property-value.css', foreground: '#edecee' },
    { token: 'variable.parameter.keyframe-list.css', foreground: '#edecee' },
    { token: 'source.css', foreground: '#edecee' },
    { token: 'support.constant.font-name', foreground: '#edecee' },
    { token: 'support.constant.vendored.property-value', foreground: '#edecee' },
    { token: 'variable.parameter', foreground: '#edecee' },
    { token: 'meta.class', foreground: '#edecee' },
    { token: 'variable', foreground: '#edecee' },
    { token: 'meta.method.declaration', foreground: '#edecee' },
    { token: 'parameter.variable.function.elixir', foreground: '#edecee' },
    { token: 'punctuation.definition.tag', foreground: '#edecee' },
    { token: 'punctuation.section.embedded', foreground: '#edecee' },
    { token: 'meta.embedded.expression', foreground: '#edecee' },
    { token: 'punctuation.terminator.dart', foreground: '#edecee' },
    { token: 'punctuation.dot.dart', foreground: '#edecee' },

    { token: 'comment', foreground: '#6d6d6d' },
    { token: 'string.quoted.docstring.multi.python', foreground: '#6d6d6d' },

    { token: 'entity.name.function', foreground: '#ffca85' },
    { token: 'support.function', foreground: '#ffca85' },

    { token: 'entity.name.type', foreground: '#82e2ff' },
    { token: 'entity.name.class', foreground: '#82e2ff' },
    { token: 'support.class.builtin', foreground: '#82e2ff' },
    { token: 'punctuation.definition.template-expression.begin', foreground: '#82e2ff' },
    { token: 'punctuation.definition.template-expression.end', foreground: '#82e2ff' },
    { token: 'entity.other.inherited-class', foreground: '#82e2ff' },
    { token: 'variable.other.constant.elixir', foreground: '#82e2ff' },
    { token: 'entity.other.attribute-name.class.css', foreground: '#82e2ff' },
    { token: 'support.class.dart', foreground: '#82e2ff' },

    { token: 'meta.parameters', fontStyle: 'italic' },
    { token: 'meta.type.parameters', fontStyle: 'italic' },
    { token: 'meta.return.type', fontStyle: 'italic' },
    { token: 'entity.name.type.interface', fontStyle: 'italic' },
    { token: 'meta.type.annotation', fontStyle: 'italic' },
    { token: 'meta.function.parameters"', fontStyle: 'italic' },
    { token: 'markup.italic.markdown', fontStyle: 'italic' }
  ]
}
export default AuraDarkTheme
